[package]
name = "mitki-inputs"
version = "0.1.0"
edition.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
camino.workspace = true
line-index = "0.1"
salsa.workspace = true
