[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.lints.rust]
unreachable_pub = "warn"
unused_qualifications = "warn"

[workspace.dependencies]
salsa = { git = "https://github.com/salsa-rs/salsa/" }
text-size = "1.1"
