format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
merge_derives = false
use_field_init_shorthand = true
use_small_heuristics = "Max"
style_edition = "2024"
wrap_comments = true
