[package]
name = "mitki"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0"
camino = "1.1"
clap = { version = "4.5", features = ["derive"] }
mitki-errors.workspace = true
salsa.workspace = true
