[package]
name = "mitki-wasm-runtime"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
mitki-abi.workspace = true
wasmparser.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true

[dev-dependencies]
mitki-comptime-wasm.workspace = true
mitki-db.workspace = true
mitki-inputs.workspace = true
wasm-encoder.workspace = true
