[package]
name = "mitki-parse"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[dependencies]
drop_bomb = "0.1"
expect-test = "1.5"
mitki-errors.workspace = true
mitki-tokenizer.workspace = true
mitki-yellow.workspace = true
salsa.workspace = true
text-size.workspace = true
