[package]
name = "mitki-comptime-wasm"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
mitki-abi.workspace = true
mitki-analysis.workspace = true
mitki-backend-wasm.workspace = true
mitki-codegen-core.workspace = true
mitki-errors.workspace = true
mitki-hir.workspace = true
mitki-inputs.workspace = true
mitki-lower.workspace = true
mitki-typeck.workspace = true
mitki-wasm-runtime.workspace = true
rustc-hash.workspace = true
salsa.workspace = true
wasmtime.workspace = true

[dev-dependencies]
mitki-db.workspace = true
