[package]
name = "mitki-errors"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
annotate-snippets = "0.11"
salsa.workspace = true
text-size.workspace = true
