[package]
name = "mitki-tokenizer"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
ascii = "1.1.0"
memchr = "2.7.4"
mitki-yellow.workspace = true
text-size.workspace = true

[dev-dependencies]
quickcheck = "1.0"
