[package]
name = "mitki-tokenizer"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
mitki-yellow.workspace = true
text-size.workspace = true
