//! Syntax and token kinds for the parser and tree.

use std::fmt::Display;

/// All token and node kinds produced by the parser.
#[allow(non_camel_case_types)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum SyntaxKind {
    LEFT_PAREN,
    RIGHT_PAREN,
    LEFT_BRACKET,
    RIGHT_BRACKET,
    LEFT_BRACE,
    RIGHT_BRACE,
    EQ,
    FAT_ARROW,
    DOT,
    DOUBLE_COLON,
    COMMA,
    COLON,
    SEMICOLON,
    FUN_KW,
    IN_KW,
    IF_KW,
    ELSE_KW,
    MATCH_KW,
    LOOP_KW,
    VAL_KW,
    VAR_KW,
    WHILE_KW,
    RETURN_KW,
    BREAK_KW,
    CONTINUE_KW,
    PUB_KW,
    USE_KW,
    AS_KW,
    STRUCT_KW,
    ENUM_KW,
    MOD_KW,
    NAME,
    TRUE_KW,
    FALSE_KW,
    INT_NUMBER,
    FLOAT_NUMBER,
    STRING,
    CHAR,
    BINARY_OPERATOR,
    POSTFIX_OPERATOR,
    PREFIX_OPERATOR,
    UNKNOWN,
    EOF,

    BIN_OP_SEQ,
    ARG_LIST,
    LOOP_EXPR,
    BREAK_EXPR,
    CONTINUE_EXPR,
    IF_EXPR,
    MATCH_EXPR,
    UNSAFE_EXPR,
    MATCH_ARM,
    ERROR,
    EXPR_STMT,
    FIELD_EXPR,
    CLOSURE_EXPR,
    FN,
    STRUCT_DEF,
    STRUCT_FIELD,
    STRUCT_FIELD_LIST,
    DESTRUCTOR_DEF,
    STRUCT_EXPR,
    STRUCT_EXPR_FIELD,
    STRUCT_EXPR_FIELD_LIST,
    ENUM_DEF,
    ENUM_VARIANT,
    ENUM_VARIANT_LIST,
    RETURN_TYPE,
    IDENT,
    PATH_EXPR,
    NAME_REF,
    TYPE_PARAM,
    LITERAL,
    TUPLE_EXPR,
    ARRAY_EXPR,
    MODULE,
    PARAM,
    PARAM_LIST,
    GENERIC_PARAM_LIST,
    GENERIC_ARG_LIST,
    PAREN_EXPR,
    POSTFIX_EXPR,
    PATH_PATTERN,
    FIELD_PATTERN,
    BINDING_PATTERN,
    WILDCARD_PATTERN,
    LITERAL_PATTERN,
    TYPED_PATTERN,
    PAREN_PATTERN,
    TUPLE_PATTERN,
    VARIANT_PATTERN,
    STRUCT_PATTERN,
    STRUCT_PATTERN_FIELD,
    PATH_TYPE,
    ARRAY_TYPE,
    FUNCTION_TYPE,
    UNION_TYPE,
    INTER_TYPE,
    RECORD_TYPE,
    TUPLE_TYPE,
    POINTER_TYPE,
    INSTANCE_ITEM,
    MOD_ITEM,
    USE_ITEM,
    PREFIX_EXPR,
    CALL_EXPR,
    STMT_LIST,
    VAL_STMT,
    ASSIGN_STMT,
    RETURN_STMT,
    TOMBSTONE,
    WHITESPACE,
    NEWLINE,
    LINE_COMMENT,
}

impl Display for SyntaxKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::LEFT_PAREN => "`(`",
            Self::RIGHT_PAREN => "`)`",
            Self::LEFT_BRACKET => "`[`",
            Self::RIGHT_BRACKET => "`]`",
            Self::LEFT_BRACE => "`{`",
            Self::RIGHT_BRACE => "`}`",
            Self::EQ => "`=`",
            Self::FAT_ARROW => "`=>`",
            Self::DOT => "`.`",
            Self::DOUBLE_COLON => "`::`",
            Self::COMMA => "`,`",
            Self::COLON => "`:`",
            Self::SEMICOLON => "`;`",
            Self::FUN_KW => "`fun`",
            Self::IF_KW => "`if`",
            Self::ELSE_KW => "`else`",
            Self::MATCH_KW => "`match`",
            Self::LOOP_KW => "`loop`",
            Self::VAL_KW => "`val`",
            Self::VAR_KW => "`var`",
            Self::WHILE_KW => "`while`",
            Self::RETURN_KW => "`return`",
            Self::BREAK_KW => "`break`",
            Self::CONTINUE_KW => "`continue`",
            Self::PUB_KW => "`pub`",
            Self::USE_KW => "`use`",
            Self::AS_KW => "`as`",
            Self::STRUCT_KW => "`struct`",
            Self::ENUM_KW => "`enum`",
            Self::MOD_KW => "`mod`",
            Self::NAME => "identifier",
            Self::INT_NUMBER => "int",
            Self::FLOAT_NUMBER => "float",
            Self::STRING => "string",
            Self::CHAR => "char",
            Self::BINARY_OPERATOR => "binary operator",
            Self::POSTFIX_OPERATOR => "postfix operator",
            Self::PREFIX_OPERATOR => "prefix operator",
            Self::UNKNOWN => "unknown",
            Self::EOF => "EOF",
            Self::WHITESPACE => "whitespace",
            Self::NEWLINE => "newline",
            Self::LINE_COMMENT => "line comment",
            _ => "<syntax node>",
        })
    }
}

impl SyntaxKind {
    /// Returns `true` if this kind represents trivia (whitespace or comments).
    #[inline]
    pub fn is_trivia(self) -> bool {
        matches!(self, Self::WHITESPACE | Self::NEWLINE | Self::LINE_COMMENT)
    }
}
